### ISSUE TITLE
marimo icon doesn't appear in JupyterHub

### ISSUE THREAD

**Issue by scls19fr** [jyio/jupyter-marimo-proxy#2]
Hello,

Following https://github.com/marimo-team/marimo/issues/905

Thanks @jyio for the great work on this JupyterHub / Marimo proxy.

I tried to install it on my own install (a VPS where JupyterHub is running behind a Traefik reverse proxy).

My install is just a bit more complex than the [minimal demo](https://gist.github.com/jyio/f4171dcb24b5b5e49fabe15d2cf9bccf) you provided.

After trying to install proxy I can't see marimo icon on the hub (when I spawn container)

Here is my `docker-compose.yml`

```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker compose configuration file
version: "3"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: latest
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - web
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
      # - "~/data:/data/shared_data:ro"  # scls: should be on spawn image
    #ports:
    #  - "8000:8000"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: ${JUPYTERHUB_ADMIN}
      # All containers will join this network
      DOCKER_NETWORK_NAME: web
      # JupyterHub will spawn this Notebook image for users
      #DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/base-notebook:latest
      #DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/julia-notebook:2024-03-06
      DOCKER_NOTEBOOK_IMAGE: custom-scls-notebook
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jupyterhub.loadbalancer.server.port=8000"
      - "traefik.http.routers.jupyterhub.rule=Host(`${JUPYTERHUB_URL}`)"
      - "traefik.http.routers.jupyterhub.entrypoints=websecure"
      - "traefik.http.routers.jupyterhub.service=jupyterhub"
      - "traefik.http.routers.jupyterhub.tls=true"
      - "traefik.http.routers.jupyterhub.tls.certresolver=default"

volumes:
  jupyterhub-data:
  jupyterhub-user-scelles:
    external: true

networks:
  web:
    external: true
```

I have two `Dockerfile`s (one for the Hub and one for spawn containers)

`Dockerfile.jupyterhub`

```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG JUPYTERHUB_VERSION
FROM quay.io/jupyterhub/jupyterhub:$JUPYTERHUB_VERSION

# Install dockerspawner, nativeauthenticator
# hadolint ignore=DL3013
RUN python3 -m pip install --no-cache-dir \
    dockerspawner \
    jupyterhub-nativeauthenticator && \
    pip install --no-cache-dir notebook 'marimo>=0.6.21' https://github.com/jyio/jupyter-marimo-proxy/archive/main.zip

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
```

I added the line

    pip install --no-cache-dir notebook 'marimo>=0.6.21' https://github.com/jyio/jupyter-marimo-proxy/archive/main.zip

but I'm not sure that it should be done there... but on

`Dockerfile.custom-scls-notebook`

```
FROM quay.io/jupyter/julia-notebook:2024-03-06

#USER root
#RUN apt-get update
#RUN apt install -f -y \
#    postgresql \
#    python3-pytest
#
#
USER $NB_UID
COPY environment.yml /tmp/environment.yml
ARG env_name=condaenv

RUN mamba env create -f /tmp/environment.yml -n $env_name && \
    mamba clean -qafy && \
    mamba run -n $env_name python -m ipykernel install --user --name=$env_name

ENV PATH /opt/conda/envs/$env_name/bin:$PATH  # added by scls

#RUN python3 -m pip install --no-cache-dir \
#    pipx \
#    nbdev \
#    python-dotenv \
#    pandas \
#    psycopg2-binary

#RUN pipx install \
#    python-dotenv \
#    poetry \
#    #nbdev

RUN pip install --no-cache-dir notebook 'marimo>=0.6.21' https://github.com/jyio/jupyter-marimo-proxy/archive/main.zip
```

Any idea why I don't see marimo icon in the spawn container?

Kind regards
